[package]
name = "track"
version = "0.1.2-dev"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]
license = "GPL-3.0-only"
edition = "2018"

[dependencies]

structopt = "0.3.9"
colored = "2.0"
im = { version = "15.0", features = ["serde"] }
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "blocking", "json"]
