[package]
name = "track"
version = "0.1.0-dev"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]

dirs = "2.0.2"
clap = "~2.33.0"
reqwest = { version = "0.10.2", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
chrono = { version = "0.4.10", features = ["serde"] }
